/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package utp.misiontic2022.c2.p53.reto4.vista;

import java.sql.SQLException;
import java.util.ArrayList;

import utp.misiontic2022.c2.p53.reto4.controlador.ControladorRequerimientos;
import utp.misiontic2022.c2.p53.reto4.modelo.vo.Requerimiento_2;

/**
 *
 * @author urano
 */
public class Requerimiento2_Panel extends javax.swing.JPanel {

    String columnas[]={"Proveedor","Constructora","Pagado"};

    public static final ControladorRequerimientos controlador = new ControladorRequerimientos();
    
    public Requerimiento2_Panel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        ArrayList<Requerimiento_2> datos;


        
        try {
            datos=controlador.consultarRequerimiento2();
        } catch (SQLException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
            datos=new ArrayList<>();
        }
        String data[][]=new String[datos.size()][3];

        //PAsando a matriz de strings
        for (int i = 0; i < datos.size(); i++) {
            data[i][0]=datos.get(i).getProveedor();
            data[i][1]=datos.get(i).getConstructora();
            data[i][2]=datos.get(i).getPagado();
        }

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            data,
            columnas
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
