/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package utp.misiontic2022.c2.p53.reto4.vista;

import java.sql.SQLException;
import java.util.ArrayList;
import utp.misiontic2022.c2.p53.reto4.controlador.ControladorRequerimientos;
import utp.misiontic2022.c2.p53.reto4.modelo.vo.Requerimiento_1;

/**
 *
 * @author urano
 */
public class Requerimiento1_Panel extends javax.swing.JPanel {
    String columna[]={"Constructora", "Ciudad", "Banco_Vinculado", "Porcentaje_Cuota_Inicial", "Clasificacion", "Fecha_Inicio"};
    ArrayList<Requerimiento_1> datos;
    public static final ControladorRequerimientos controlador = new ControladorRequerimientos();
    /**
     * Creates new form Requerimiento1
     */
    public Requerimiento1_Panel() {
        initComponents();
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaDatos = new javax.swing.JTable();
        
        //Pasando los datos a una matriz para luego pasarla a la tabla
        try {
            datos=controlador.consultarRequerimiento1();
        } catch (SQLException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
            datos=new ArrayList<>();
        }
        String datosMatriz[][]=new String[datos.size()][6];
        for (int i = 0; i < datos.size(); i++) {
            datosMatriz[i][0]=datos.get(i).getConstructora();
            datosMatriz[i][1]=datos.get(i).getCiudad();
            datosMatriz[i][2]=datos.get(i).getBanco();
            datosMatriz[i][3]=datos.get(i).getPorcentaje()+"";
            datosMatriz[i][4]=datos.get(i).getClasificacion();
            datosMatriz[i][5]=datos.get(i).getFecha();
        }

        tablaDatos.setModel(new javax.swing.table.DefaultTableModel(
            datosMatriz,
            columna
        ));
        jScrollPane1.setViewportView(tablaDatos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaDatos;
    // End of variables declaration//GEN-END:variables

    
}
